### ISSUE TITLE
maybe support bc7?

### ISSUE THREAD

**Issue by MisssThe** [aras-p/UnityGPUTexCompression#1]

**Comment by aras-p** [comment]
This project is only an example "if you have a compute shader that does texture compression, here's how you would plug that into Unity". If you have a compute shader that does BC7 compression, plug it the same way as others are in this project!

I don't have a compute shader that does BC7 in any decent way. Last time I tried (four years ago) -- https://github.com/aras-p/bc7e-on-gpu -- it had all sorts of problems.
